In [229]:
import pandas as pd
import numpy as np
from numpy import *

In [230]:
model1 = pd.read_csv('factorization.csv')
model2 = pd.read_csv('RandomForest.csv')
model3 = pd.read_csv('gradient_boosted_tree.csv')
model4 = pd.read_csv('decisionTree.csv')
model5 = pd.read_csv('SVM.csv')
model6 = pd.read_csv('logisticRegression.csv')
model7 = pd.read_csv('prediction_mean.csv')

In [231]:
def sortResults (modelResults):

  modelResults['UserID'] = modelResults['TrackID'].str.split('_').str[0].astype(int)
  modelResults['TrackID'] = modelResults['TrackID'].str.split('_').str[1].astype(int)
  modelResults = modelResults.sort_values(by=['UserID','TrackID'])
  return modelResults

In [232]:
model1 = sortResults(model1)
model2 = sortResults(model2)
model3 = sortResults(model3)
model4 = sortResults(model4)
model5 = sortResults(model5)
model6 = sortResults(model6)
model7 = sortResults(model7)


In [233]:
model1.Predictor.replace(0,-1,inplace= True)
model2.Predictor.replace(0,-1,inplace= True)
model3.Predictor.replace(0,-1,inplace= True)
model4.Predictor.replace(0,-1,inplace= True)
model5.Predictor.replace(0,-1,inplace= True)
model6.Predictor.replace(0,-1,inplace= True)
model7.Predictor.replace(0,-1,inplace= True)


In [234]:
s1 = model1.Predictor.tolist()
s2 = model2.Predictor.tolist()
s3 = model3.Predictor.tolist()
s4 = model4.Predictor.tolist()
s5 = model5.Predictor.tolist()
s6 = model6.Predictor.tolist()
s7 = model7.Predictor.tolist()



S=np.transpose(mat([s1,s2,s3,s4,s6,s7])) #customize here
print(S)

[[-1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]
 ...
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]]


In [235]:
score1 = 0.85567
score2 = 0.85575
score3 = 0.85564
score4 = 0.85567
score5 = 0.84660
score6 = 0.85526
score7 = 0.84797

score_mat=np.transpose(mat([score1,score2,score3,score4,score6, score7])) #customize here
k=120000 #number of samples
STx=k*(2*score_mat-1)

print(STx)

[[85360.8]
 [85380. ]
 [85353.6]
 [85360.8]
 [85262.4]]


In [236]:
STS=np.transpose(S)*S
STS_inverse=np.linalg.pinv(STS)

a=STS_inverse*STx
S_new=S*a
S_new=S_new.T
new_S=np.array(S_new).reshape((20000,6)).tolist()
print(new_S)

[[-0.7166741821333189, 0.7166741821333189, -0.7166741821333189, 0.7166741821333189, -0.7166741821333189, -0.7166741821333189], [-0.7166741821333189, 0.7166741821333189, 0.7166741821333189, -0.7166741821333189, 0.7166741821333189, -0.7166741821333189], [-0.7166741821333189, 0.7166741821333189, 0.7166741821333189, -0.7166741821333189, 0.7166741821333189, 0.7166741821333189], [-0.7166741821333189, -0.7166741821333189, -0.7166741821333189, 0.7166741821333189, 0.7166741821333189, 0.7166741821333189], [0.7166741821333189, 0.7166741821333189, -0.7166741821333189, -0.7166741821333189, 0.7166741821333189, 0.7166741821333189], [0.7166741821333189, -0.7166741821333189, 0.7166741821333189, 0.7166741821333189, -0.7166741821333189, -0.7166741821333189], [0.7166741821333189, -0.7166741821333189, 0.7166741821333189, -0.7166741821333189, 0.7166741821333189, -0.7166741821333189], [0.7166741821333189, 0.7166741821333189, -0.7166741821333189, 0.7166741821333189, -0.7166741821333189, -0.7166741821333189], 

In [237]:
def prediction_table(grades_table):
    prediction_table = [0 for i in range(len(grades_table)*6)]
    for i in range(len(grades_table)):
        x = np.array(grades_table[i])
        x = x.argsort()

        for k in range(6):
            if k<3:
                prediction_table[i * 6 + x[k]] = 0
            else:
                prediction_table[i * 6 + x[k]] = 1
      
    return prediction_table

In [238]:
new_ratings_table = prediction_table(new_S)

In [239]:
model2.Predictor = new_ratings_table #overwrite predictions

In [240]:
model2

TrackID  Predictor  UserID
2          9903          0  199810
4         18515          1  199810
1         74139          0  199810
5        105760          1  199810
0        208019          0  199810
...         ...        ...     ...
119996    86104          0  249010
119994   110470          1  249010
119997   186634          1  249010
119999   262811          1  249010
119998   293818          0  249010

[120000 rows x 3 columns]

In [241]:
model2['TrackID'] = model2['UserID'].astype(str) + '_' + model2['TrackID'].astype(str) #format for submission
model2['TrackID'] = model2['TrackID'].astype(str)
model2 = model2.drop("UserID",axis=1)
model2

TrackID  Predictor
2         199810_9903          0
4        199810_18515          1
1        199810_74139          0
5       199810_105760          1
0       199810_208019          0
...               ...        ...
119996   249010_86104          0
119994  249010_110470          1
119997  249010_186634          1
119999  249010_262811          1
119998  249010_293818          0

[120000 rows x 2 columns]

In [242]:
model2.to_csv('ensemble36.csv',index = False)